import type { AppProps } from 'next/app'
import Head from "next/head"
import { useRouter } from "next/router"
import { CookiesProvider, useCookies } from 'react-cookie'
import { ToastContainer } from 'react-toastify'
import NavBar from "../lib/Components/NavBar"
import 'react-toastify/dist/ReactToastify.css'
import 'bootstrap/dist/css/bootstrap.css'
import '../styles/globals.css'
import { useEffect } from 'react'

export default function App({ Component, pageProps }: AppProps) {
  const currentPath = useRouter().pathname
  const [_cookie, setCookie, removeCookie] = useCookies(['auth_token'])
  const mainPages = ['/', '/auth']
  const mainPage = mainPages.findIndex(page => currentPath === page)

  useEffect(() => {
    const auth_token = localStorage.getItem('auth_token')

    if (auth_token)
      setCookie('auth_token', auth_token, { path: '/' })
    else
      removeCookie('auth_token')
  })

  return (
    <CookiesProvider>
      <Head>
        <title>Remember It - A Calendar App</title>
        <meta name="description" content="Remember It - A Calendar App generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar showSide={ mainPage === -1 }/>
      <main>
        <Component {...pageProps} />
      </main>

      <ToastContainer
          position="top-right"
          hideProgressBar
          newestOnTop
          pauseOnFocusLoss
          theme="colored"
      />
    </CookiesProvider>
  )
}
